on: 
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  job-name:
    runs-on: ubuntu-latest
    name: First github action job
    steps:
      - uses: octokit/request-action@v2.x
          id: create_check_run
          with:
            route: POST /repos/{owner}/{repo}/check-runs
            owner: octokit
            repo: request-action
            name: "Test check run"
            head_sha: ${{ github.sha }}
            output: | # The | is significant!
              title: Test check run title
              summary: A summary of the test check run
              images:
                - alt: Test image
                  image_url: https://octodex.github.com/images/jetpacktocat.png
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
