on: 
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  Veracode-checks:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub API Request to create a check
        uses: octokit/request-action@v2.1.0
        id: get_latest_release
        with:
          route: GET /repos/GitHubVeracode/example-javascript/releases/latest
          owner: GitHubVeracode
          repo: ${{ github.event.repository.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo latest release: '${{ steps.get_latest_release.outputs.data }}'"
      - name: Create metadata
        id: create-metadata-json
        run: |
          echo '{
            "check_run_type": "check_run_type_value",
            "repository_name": "repository_name_value",
            "check_run_id": "check_run_id_value"
          }' > workflow-metadata.json
        shell: bash
      - name: Save metadata
        uses: actions/upload-artifact@v3
        with:
          name: workflow-metadata
          path: workflow-metadata.json
      - run: "echo latest release: '${{ steps.get_latest_release.outputs.data }}'"

      
