on: 
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  job-name:
    runs-on: ubuntu-latest
    name: First github action job
    steps:
      - name: Every time
        run: echo "This step will always run"
      - name: Create metadata
        id: create-metadata-json
        run: |
          echo '{
            "check_run_type": "check_run_type_value",
            "repository_name": "repository_name_value",
            "check_run_id": "check_run_id_value"
          }' > workflow-metadata.json
          shell: bash
      - name: Save metadata
        uses: actions/upload-artifact@v3
        with:
          name: workflow-metadata
          path: workflow-metadata.json
