on: 
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  job-name:
    runs-on: ubuntu-latest
    name: First github action job
    steps:
      - name: Every time
        run: echo "This step will always run"
