on: 
  push:
    branches: [ "master" ]
permissions:
    contents: write
    actions: write
    checks: write
jobs:
  Veracode-checks:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub API Request to releases tag
        uses: octokit/request-action@v2.1.0
        id: get_latest_release
        with:
          route: GET /repos/GitHubVeracode/example-javascript/releases/latest
          owner: GitHubVeracode
          repo: ${{ github.event.repository.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo latest release: '${{ steps.get_latest_release.outputs.data }}'"
      # Create check run
      - name: GitHub API Request to create a check
        uses: octokit/request-action@v2.x
        id: create_check_run
        with:
          route: POST /repos/{owner}/{repo}/check-runs
          owner: GitHubVeracode
          repo: ${{ github.event.repository.name }}
          name: "Test check run"
          head_sha: ${{ github.sha }}
          status: in_progress
          output: | # The | is significant!
            title: Test check run title
            summary: A summary of the test check run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create metadata
        id: create-metadata-json
        run: |
          echo '{
            "check_run_type": "check_run_type_value",
            "repository_name": "repository_name_value",
            "check_run_id": ${{ steps.create_check_run.outputs.id }}
            
          }' > workflow-metadata.json
        shell: bash
      - name: Save metadata
        uses: actions/upload-artifact@v3
        with:
          name: workflow-metadata
          path: workflow-metadata.json
      - run: "echo latest release: '${{ steps.create_check_run.outputs.data }}'"

      
